### ISSUE TITLE
如何去除生成的html里的#

### ISSUE THREAD

**Issue by Zhiqiang-UD** [Vevlins/toki#2]
非常喜欢这个主题，感谢！有一个小小的疑问。
我注意到如果有header用了#，##或###, 那在生成的html里仍然会保留#符号。这个能去掉吗？它的作用是什么？是不是为了开始的table of content？

**Comment by vevlins** [comment]
显示#是hexo自己默认的，其目的主要有三：
+ 根据#提供目录，最终不同的#被渲染成不同层级的h标签如h1\h2\h3等
+ 提供目录到指定#的跳转，添加锚点
+ 更清楚地表示层级

如果不喜欢可以进行一点小改造，对h标签下的a都隐藏掉，a就是显示`##`的标签

``` css
h1 a,h2 a,h3 a,h4 a,h5 a,h6 a{
   display:none
}
```
